export interface Tech {
  readonly name: string;
  readonly logo: string;
}

export interface SkillGroup {
  readonly id: string;
  readonly heading: string;
  readonly items: readonly Tech[];
}

/** Icon files are generated by `npm run icons` — see scripts/build-tech-icons.mjs. */
const logo = (file: string) => `/media/tech/${file}.svg`;

export const SKILL_GROUPS: readonly SkillGroup[] = [
  {
    id: 'languages',
    heading: 'Languages',
    items: [
      { name: 'Python', logo: logo('python') },
      { name: 'C', logo: logo('c') },
      { name: 'C++', logo: logo('cpp') },
      { name: 'C#', logo: logo('csharp') },
      { name: 'TypeScript', logo: logo('typescript') },
      { name: 'JavaScript', logo: logo('javascript') },
      { name: 'SQL', logo: logo('sql') },
      { name: 'Bash', logo: logo('bash') },
      { name: 'HTML5', logo: logo('html5') },
      { name: 'CSS3', logo: logo('css3') },
    ],
  },
  {
    id: 'frameworks',
    heading: 'Frameworks & Libraries',
    items: [
      { name: 'React', logo: logo('react') },
      { name: 'Next.js', logo: logo('nextjs') },
      { name: 'Vue.js', logo: logo('vuejs') },
      { name: 'Node.js', logo: logo('nodejs') },
      { name: 'Django', logo: logo('django') },
      { name: 'FastAPI', logo: logo('fastapi') },
      { name: 'Tailwind CSS', logo: logo('tailwind') },
      { name: 'PyTorch', logo: logo('pytorch') },
      { name: 'Hugging Face', logo: logo('huggingface') },
      { name: 'Vite', logo: logo('vite') },
    ],
  },
  {
    id: 'databases',
    heading: 'Databases',
    items: [
      { name: 'PostgreSQL', logo: logo('postgresql') },
      { name: 'MySQL', logo: logo('mysql') },
      { name: 'MongoDB', logo: logo('mongodb') },
      { name: 'Supabase', logo: logo('supabase') },
      { name: 'Firebase', logo: logo('firebase') },
      { name: 'Redis', logo: logo('redis') },
      { name: 'DynamoDB', logo: logo('dynamodb') },
      { name: 'ChromaDB', logo: logo('chromadb') },
    ],
  },
  {
    id: 'devops',
    heading: 'DevOps & Tools',
    items: [
      { name: 'Git', logo: logo('git') },
      { name: 'Docker', logo: logo('docker') },
      { name: 'Jenkins', logo: logo('jenkins') },
      { name: 'Linux', logo: logo('linux') },
      { name: 'GCP', logo: logo('gcp') },
      { name: 'AWS Lambda', logo: logo('awslambda') },
    ],
  },
];
